### ISSUE TITLE
"Instance of 'InstantiationException'" on Android build

### ISSUE THREAD

**Issue by anefjodov** [heremaps/here-sdk-ref-app-flutter#108]
When I try to run downloaded project. 
I'm trying to run application with HERE SDK version 4.15.5. Also try to add HERE SDK 4.16.1. 

Full error message:
```
The following InstantiationException was thrown building Consumer2<AppPreferences, CustomMapStyleSettings>(dirty, dependencies: [_InheritedProviderScope<AppPreferences?>, _InheritedProviderScope<CustomMapStyleSettings?>, _InheritedTheme, _LocalizationsScope-[GlobalKey#1046e]]):
Instance of 'InstantiationException'

The relevant error-causing widget was:
Consumer2<AppPreferences, CustomMapStyleSettings> Consumer2:file:///C:/src/here/here_reference_app/here-sdk-ref-app-flutter-master-v.4.15.5/lib/landing_screen.dart:109:12
When the exception was thrown, this was the stack:
#0 ConsentInternal$Impl.fromSharedSdkNativeEngine (package:here_sdk/src/sdk/consent/consent_internal.dart:191:11)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/1 ConsentInternal.fromSharedSdkNativeEngine (package:here_sdk/src/sdk/consent/consent_internal.dart:46:68)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/2 new ConsentEngine (package:here_sdk/src/sdk/consent/consent_engine.dart:25:63)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/3 PositioningEngine._consentEngine (package:RefApp/positioning/positioning_engine.dart:34:69)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/4 PositioningEngine._consentEngine (package:RefApp/positioning/positioning_engine.dart)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/5 PositioningEngine.userConsentState (package:RefApp/positioning/positioning_engine.dart:51:45)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/6 _LandingScreenState._buildUserConsentItems (package:RefApp/landing_screen.dart:195:39)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/7 _LandingScreenState._buildDrawer (package:RefApp/landing_screen.dart:367:16)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/8 _LandingScreenState.build. (package:RefApp/landing_screen.dart:122:17)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/9 Consumer2.buildWithChild (package:provider/src/consumer.dart:206:19)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/10 SingleChildStatelessWidget.build (package:nested/nested.dart:259:41)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/11 StatelessElement.build (package:flutter/src/widgets/framework.dart:5367:49)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/12 SingleChildStatelessElement.build (package:nested/nested.dart:279:18)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/13 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297:15)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/14 Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/15 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279:5)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/16 ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
https://github.com/heremaps/here-sdk-ref-app-flutter/pull/17 SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
... Normal element mounting (228 frames)
#245 Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#246 MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
#247 MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
... Normal element mounting (447 frames)
#694 _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
... Normal element mounting (7 frames)
#701 SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
... Normal element mounting (7 frames)
#708 _NestedHookElement.mount (package:nested/nested.dart:187:11)
... Normal element mounting (7 frames)
#715 _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
... Normal element mounting (7 frames)
#722 SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
... Normal element mounting (7 frames)
#729 _NestedHookElement.mount (package:nested/nested.dart:187:11)
... Normal element mounting (7 frames)
#736 _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
... Normal element mounting (7 frames)
#743 SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
... Normal element mounting (7 frames)
#750 _NestedHookElement.mount (package:nested/nested.dart:187:11)
... Normal element mounting (7 frames)
#757 _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
... Normal element mounting (7 frames)
#764 SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
... Normal element mounting (7 frames)
#771 _NestedHookElement.mount (package:nested/nested.dart:187:11)
... Normal element mounting (7 frames)
#778 _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
... Normal element mounting (7 frames)
#785 SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
... Normal element mounting (7 frames)
#792 _NestedHookElement.mount (package:nested/nested.dart:187:11)
... Normal element mounting (7 frames)
#799 _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
... Normal element mounting (7 frames)
#806 SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
... Normal element mounting (7 frames)
#813 _NestedHookElement.mount (package:nested/nested.dart:187:11)
... Normal element mounting (7 frames)
#820 SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
... Normal element mounting (35 frames)
#855 Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#856 Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)
#857 RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1253:16)
#858 RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1222:5)
#859 RenderObjectToWidgetAdapter.attachToRenderTree. (package:flutter/src/widgets/binding.dart:1169:18)
#860 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719:19)
#861 RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1168:13)
#862 WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1001:7)
#863 WidgetsBinding.scheduleAttachRootWidget. (package:flutter/src/widgets/binding.dart:981:7)
#867 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
```

**Comment by stefan-troyke** [comment]
The initialisation of the SDK Native enigne changed between 4.15.0.0 and 4.16.0.0. The integation of 4.16.0.0 will start soon and we will fix the issue.

**Comment by mr-pant** [comment]
The new SDK version 4.16.0.0 is integrated with https://github.com/heremaps/here-sdk-ref-app-flutter/pull/111 and has changes related to the new initialisation. Please go through readme on how to handle new initialisation.
